basePath: /
definitions:
  main.APIResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
  main.Category:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  main.Product:
    properties:
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      stock:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for product management
  title: Product API
  version: "1.0"
paths:
  /api/categories:
    get:
      description: Retrieve all category data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.APIResponse'
      summary: Get all categories
      tags:
      - categories
    post:
      description: Add a new category
      parameters:
      - description: Category Data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/main.Category'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.APIResponse'
      summary: Add new category
      tags:
      - categories
  /api/categories/{id}:
    delete:
      description: Delete category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.APIResponse'
      summary: Delete category
      tags:
      - categories
    get:
      description: Retrieve category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.APIResponse'
      summary: Get category by ID
      tags:
      - categories
    put:
      description: Update category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category Data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/main.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.APIResponse'
      summary: Update category
      tags:
      - categories
  /api/products:
    get:
      description: Retrieve all product data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.APIResponse'
      summary: Get all products
      tags:
      - products
    post:
      description: Add a new product
      parameters:
      - description: Product Data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/main.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.APIResponse'
      summary: Add new product
      tags:
      - products
  /api/products/{id}:
    delete:
      description: Delete product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.APIResponse'
      summary: Delete product
      tags:
      - products
    get:
      description: Retrieve product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.APIResponse'
      summary: Get product by ID
      tags:
      - products
    put:
      description: Update product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product Data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/main.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.APIResponse'
      summary: Update product
      tags:
      - products
swagger: "2.0"
